[package]
name = "weetun"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
socket2 = "0.6.1"
tokio = { version = "1.48.0", features = ["full"] }
tokio-tun = { path = "../tokio-tun" }
utuntap = "0.3.1"
